blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

mundo_aberto/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path

urlpatterns = [
    path('', include('blog.urls')),
    path('places/', include('places.urls')),
    path('admin/', admin.site.urls),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')), # fix favicon in development
]

places/urls.py
from django.urls import path

from . import views

app_name = 'places'
urlpatterns = [
    path('',                 views.PlaceListView.as_view(),   name='index'),
    path('create/',          views.PlaceCreateView.as_view(), name='create'),
    path('search/',          views.PlaceSearchView.as_view(), name='search'),
    path('<int:pk>/',        views.PlaceDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PlaceUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PlaceDeleteView.as_view(), name='delete'),

    path('<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment'),

    path('categories/',                 views.CategoryListView.as_view(),   name='categories'),
    path('categories/<int:pk>/',        views.CategoryDetailView.as_view(), name='detail-category'),
    path('categories/create',           views.CategoryCreateView.as_view(), name='create-category'),
    path('categories/delete/<int:pk>/', views.CategoryDeleteView.as_view(), name='delete-category'),
]

blog/models.py
from django.db import models

places/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    name = models.CharField(max_length=255)
    info = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    picture = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return f'/places/{self.pk}' 


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    place = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date'] # Ordena pela coluna 'date', mais recente primeiro

    def __str__(self):
        return f'{self.author} at {self.date}'


class Category(models.Model):
    name = models.CharField(max_length=255)
    info = models.TextField()
    places = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}: {self.info}'

places/forms.py
from django.forms.widgets import CheckboxSelectMultiple
from django.forms import ModelForm
from .models import Category, Post, Comment

class PlaceForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'info',
            'picture',
        ]
        labels = {
            'name': 'Lugar',
            'info': 'Descrição',
            'picture': 'Imagem (URL)',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Nome',
            'text': 'Comentário',
        }

class CategoryForm(ModelForm):    
    class Meta:
        model = Category
        fields = [
            'name',
            'info',
            'places'
        ]
        labels = {
            'name'   : 'Região',
            'info'   : 'Descrição',
            'places' : 'Lugares',
        }
    
    # Many-to-many: lista de itens para checkboxes
    def __init__(self, *args, **kwargs):        
        super(CategoryForm, self).__init__(*args, **kwargs)
        
        self.fields["places"].widget = CheckboxSelectMultiple()
        self.fields["places"].queryset = Post.objects.all()

blog/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'blog/index.html', {})

def about(request):
    return render(request, 'blog/about.html', {})

places/views.py
from django.views import generic
from django.urls import reverse_lazy

from .models import Post, Category
from .forms import CategoryForm, PlaceForm, CommentForm


# ====== #
# CREATE #
# ====== #

class PlaceCreateView(generic.CreateView):
    form_class = PlaceForm
    template_name = 'places/create.html'
    context_object_name = 'place'

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse_lazy('places:detail', args=(self.object.id, ))

class CommentCreateView(generic.CreateView):
    form_class = CommentForm
    template_name = 'places/comment.html'
    context_object_name = 'commment'

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse_lazy('places:detail', kwargs={'pk' : pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # context padrão
        context['place'] = Post.objects.get(pk=self.kwargs.get('pk')) # Adiciona o post ao context
        return context
    
    def form_valid(self, form):
        form.instance.place_id = self.kwargs.get('pk')
        return super().form_valid(form)

class CategoryCreateView(generic.CreateView):
    form_class = CategoryForm
    template_name = 'places/create_category.html'

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse_lazy('places:detail-category', args=(self.object.id, ))

# ==== #
# READ #
# ==== #

class PlaceDetailView(generic.DetailView):
    model = Post
    template_name = 'places/detail.html'
    context_object_name = 'place'

class PlaceListView(generic.ListView):
    model = Post
    template_name = 'places/index.html'
    context_object_name = 'places_list'

class PlaceSearchView(generic.ListView):
    model = Post
    template_name = 'places/search.html'
    context_object_name = 'places_list'

    def get_queryset(self):
        search = self.request.GET.get('place_name', '')
        return Post.objects.filter(name__icontains=search)

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'places/detail_category.html'
    context_object_name = 'category'

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'places/categories.html'
    context_object_name = 'categories_list'

# ====== #
# UPDATE #
# ====== #

class PlaceUpdateView(generic.UpdateView):
    model = Post
    template_name = 'places/update.html'
    context_object_name = 'place'
    fields = ['name', 'info', 'picture']

# ====== #
# DELETE #
# ====== #

class PlaceDeleteView(generic.DeleteView):
    model = Post
    template_name = 'places/delete.html'
    context_object_name = 'place'
    success_url = reverse_lazy('places:index')

class CategoryDeleteView(generic.DeleteView):
    model = Category
    template_name = 'places/delete_category.html'
    context_object_name = 'category'
    success_url = reverse_lazy('places:categories')

blog/templates/blog/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Sobre {% endblock title %}

{% block content %}

    <header class="intro">
        <img class="intro-pic" src="{% static 'images/about.jpg' %}" alt='about-pic' />
        <h2>Sobre</h2>
    </header>
    <article class="description">
        <p>
            Viaje sem preocupações com o <b>Mundo Aberto</b>! 
            Nosso guia é a sua bússola para descobrir o próximo destino da sua jornada. 
            Encontre rapidamente os principais pontos turísticos de cada lugar, e ainda saiba quais eventos estarão acontecendo durante sua aventura! 
            Trazemos informações essenciais para que você se prepare antecipadamente e aproveite ao máximo sua viagem!
        </p>
    </article>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Início {% endblock title %}

{% block content %}

    <article class="land">
        <img src="{% static 'images/land.jpg' %}" alt="landpage-pic">
        <section class="land-title">
            <h1 id='mundo_aberto'>Mundo Aberto</h1>
            <h2 id='guia-de-viagem'>Guia de Viagem</h2>
        </section>
    </article>
    <article class="features">
        {% include "components/feature.html" with 
            feature_pic="static/images/beach-icon.png" 
            feature_name="Pontos Turísticos" 
            feature_desc="Antecipe-se à emoção! Descubra os tesouros escondidos de cada destino, garantindo que sua jornada seja repleta dos melhores momentos e experiências inesquecíveis!" %}
            
        {% include "components/feature.html" with 
            feature_pic="static/images/pamphlet-icon.png" 
            feature_name="Dicas" 
            feature_desc="Encontre tudo que precisa para transformar seu sonho de viagem em realidade, sem surpresas no caminho!" %}

        {% include "components/feature.html" with 
            feature_pic="static/images/ticket-icon.png" 
            feature_name="Atrações" 
            feature_desc="Explore as singularidades de cada destino, mergulhe em eventos exclusivos e descubra atrações que tornarão sua experiência única e memorável!" %}
    </article>

{% endblock content %}

places/templates/places/categories.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Regiões {% endblock title %}

{% block content %}

<header class='intro'>
    <img class="intro-pic" src="{% static 'images/list.jpg' %}" alt="list-pic">
    <h2>Regiões</h2>
    <section class='more'>
        <a href="{% url 'places:create-category' %}">
            <button class="primary-button">Criar</button>
        </a>
    </section>
</header>
<article class='category-cards-list'>
    {% for category in categories_list %}

    {% include "components/category_card.html" with
        card_id=category.id
        card_name=category.name %}

    {% endfor %}
</article>

{% endblock content %}

places/templates/places/comment.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Comentar: {{ place.name }} {% endblock title %}

{% block content %}

<header class='intro'>
    <img class="intro-pic" src="{% static 'images/create.jpg' %}" alt="create-pic">
    <h2>Comentar</h2>
    <h3>{{ place.name }}</h3>
    <section class='more'>
        <a href="{% url 'places:detail' pk=place.pk %}">
            <button class="secondary-button">Voltar</button>
        </a>
    </section>
</header>
<article class="formulary">
    <form method="POST" action="{% url 'places:comment' pk=place.pk %}" >
        {% csrf_token %}
        <section class='form-field'>
            {{ form.author.label_tag }}
            {{ form.author }}
        </section>
        <section class='form-field'>
            {{ form.text.label_tag }}
            {{ form.text }}
        </section>
        <button class="primary-button" type="submit">Publicar</button>
    </form>
</article>

{% endblock content %}

places/templates/places/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Novo Lugar {% endblock title %}

{% block content %}

<header class="intro">
    <img class="intro-pic" src="{% static 'images/create.jpg' %}" alt="create-pic">
    <h2>Novo lugar</h2>
</header>
<article class="formulary">
    <form method="POST" action="{% url 'places:create' %}">
        {% csrf_token %}
        <section class='form-field'>
            {{ form.name.label_tag }}
            {{ form.name }}
        </section>
        <section class='form-field'>
            {{ form.info.label_tag }}
            {{ form.info }}
        </section>
        <section class='form-field'>
            {{ form.picture.label_tag }}
            {{ form.picture }}
        </section>
        <button class="primary-button" type="submit">Adicionar</button>
    </form>
</article>

{% endblock content %}

places/templates/places/create_category.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Nova Categoria {% endblock title %}

{% block content %}

<header class="intro">
    <img class="intro-pic" src="{% static 'images/create.jpg' %}" alt="create-pic">
    <h2>Nova categoria</h2>
</header>
<article class="formulary">
    <form action="{% url 'places:create-category' %}" method="POST">
        {% csrf_token %}
        <section class='form-field'>
            {{ form.name.label_tag }}
            {{ form.name }}
        </section>
        <section class='form-field'>
            {{ form.info.label_tag }}
            {{ form.info }}
        </section>
        <section class='form-checkbox'>
            {{ form.places.label_tag }}
            {{ form.places }}
        </section>
        <button class="primary-button" type="submit">Criar</button>
    </form>
</article>

{% endblock content %}

places/templates/places/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Excluir: {{ place.name }} {% endblock title %}

{% block content %}

<header class='intro'>
    <img class="intro-pic" src="{% static 'images/delete.jpg' %}" alt="delete-pic">
    <h2>Excluir</h2>
    <h3>{{ place.name }}</h3>
    <section class='more'>
        <a href="{% url 'places:detail' pk=place.pk %}">
            <button class="secondary-button">Voltar</button>
        </a>
    </section>
</header>
<article class="formulary">
    <p class="delete-text">Realmente deseja remover o lugar?</p>
    <form action="{% url 'places:delete' place.pk %}" method="post">
        {% csrf_token %}        
        <button class="delete-button" type="submit">Apagar</button>
    </form>
</article>

{% endblock content %}

places/templates/places/delete_category.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Excluir: {{ category.name }} {% endblock title %}

{% block content %}

<header class='intro'>
    <img class="intro-pic" src="{% static 'images/delete.jpg' %}" alt="delete-pic">
    <h2>Excluir</h2>
    <h3>{{ category.name }}</h3>
    <section class='more'>
        <a href="{% url 'places:detail-category' pk=category.pk %}">
            <button class="secondary-button">Voltar</button>
        </a>
    </section>
</header>
<article class="formulary">
    <p class="delete-text">Realmente deseja remover o lugar?</p>
    <form action="{% url 'places:delete-category' pk=category.pk %}" method="POST">
        {% csrf_token %}        
        <button class="delete-button" type="submit">Apagar</button>
    </form>
</article>

{% endblock content %}

places/templates/places/detail.html
{% extends 'base.html' %}

{% block title %} {{ place.name }} {% endblock title %}

{% block content %}

<header class="intro">
    <img class="intro-pic" src='{{ place.picture }}' alt='place-pic' />
    <h2>{{ place.name }}</h2>
    <section class="more">
        <a href="{% url 'places:update' pk=place.pk %}">
            <button class="primary-button">Editar</button>
        </a>
        <a href="{% url 'places:delete' pk=place.pk %}">
            <button class="delete-button">Apagar</button>
        </a>
    </section>
    <p class="place-date"><b>Criado em:</b> {{ place.date | date:"Y/n/j" }} às {{ place.date | time:"H:i:s"}}</p>
</header>
<article class="description">
    {{ place.info | safe | linebreaks }}
</article>

{% if place.category_set.all %}
<header class="intro">
    <h3>Regiões</h3>
</header>
<article class='category-cards-list'>
    {% for category in place.category_set.all %}

    {% include "components/category_card.html" with
        card_id=category.id
        card_name=category.name %}

    {% endfor %}
</article>
{% endif %}

<header class="intro">
    <h3>Comentários</h3>
</header>
<article class="comments">
    {% if place.comment_set.all %}
        {% for comment in place.comment_set.all %}

        {% include "components/comment_card.html" with
        card_author=comment.author
        card_text=comment.text 
        card_date=comment.date %}

        {% endfor %}
    {% else %}
        <p>Ainda não existem comentários, seja o primeiro!</p>
    {% endif %}
    <a href="{% url 'places:comment' place.pk %}">
        <button class="primary-button">Comentar</button>
    </a>
</article>

{% endblock content %}

places/templates/places/detail_category.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ category.name }} {% endblock title %}

{% block content %}

<header class="intro">
    <img class="intro-pic" src="{% static 'images/detail.jpg' %}" alt="detail-pic"/>
    <h2>{{ category.name }}</h2>
    <section class="more">        
        <a href="{% url 'places:delete-category' pk=category.pk %}">
            <button class="delete-button">Apagar</button>
        </a>
    </section>
</header>
<article class="description">
    {{ category.info | linebreaks }}
</article>

{% if category.places.all %}

<header class="intro">
    <h3>Regiões</h3>
</header>
<article class='category-cards-list'>
    {% for place in category.places.all %}

    {% include "components/place_card.html" with
        card_id=place.id
        card_name=place.name 
        card_date=place.date
        card_picture=place.picture %}

    {% endfor %}
</article>
{% endif %}

{% endblock content %}

places/templates/places/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Lugares {% endblock title %}

{% block content %}

<header class='intro'>
    <img class="intro-pic" src="{% static 'images/list.jpg' %}" alt="list-pic" />
    <h2>Lugares</h2>
    <section class='more'>
        <a href="{% url 'places:search' %}">
            <button class="primary-button">Buscar</button>
        </a>
        <a href="{% url 'places:create' %}">
            <button class="primary-button">Criar</button>
        </a>
    </section>
</header>
<article class='place-cards-list'>
    {% for place in places_list %}

    {% include "components/place_card.html" with
        card_id=place.id
        card_name=place.name 
        card_date=place.date
        card_picture=place.picture %}

    {% endfor %}
</article>

{% endblock content %}

places/templates/places/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Buscar {% endblock title %}

{% block content %}

<header class='intro'>
    <img class="intro-pic" src="{% static 'images/list.jpg' %}" alt="list-pic">
    <h2>Busca</h2>
</header>
<article class='search'>
    <form action="{% url 'places:search' %}" method="GET">
        <section class="form-field">
            <label for="place_name">Lugar</label>
            <input type="text" name="place_name" id="place_name" />
        </section>
        <button class="primary-button" type="submit">Pesquisar</button>
    </form>
</article>

<header class='intro'>
    <h2>Resultados</h2>
</header>
<article class='place-cards-list'>
    {% if places_list %}
    {% for place in places_list %}

    {% include "components/place_card.html" with
        card_id=place.id
        card_name=place.name 
        card_date=place.date
        card_picture=place.picture %}

    {% endfor %}
    {% else %}
    <p>Não foi encontrado nenhum resultado para essa busca.</p>
    {% endif %}
</article>

{% endblock content %}

places/templates/places/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Atualizar: {{ place.name }} {% endblock title %}

{% block content %}

<header class='intro'>
    <img class="intro-pic" src="{% static 'images/create.jpg' %}" alt="create-pic" />
    <h2>Atualizar</h2>
    <h3>{{ place.name }}</h3>
</header>
<article class="formulary">
    <form method="POST" action="{% url 'places:update' place.pk %}">
        {% csrf_token %}
        <section class='form-field'>
            {{ form.name.label_tag }}
            {{ form.name }}
        </section>
        <section class='form-field'>
            {{ form.info.label_tag }}
            {{ form.info }}
        </section>
        <section class='form-field'>
            {{ form.picture.label_tag }}
            {{ form.picture }}
        </section>
        <button class="primary-button" type="submit">Atualizar</button>
    </form>
</article>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>

<head>
    <html lang="br"></html>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <title>Mundo Aberto | {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include 'components/header.html' %}

    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>

    {% include 'components/footer.html' %}  
</body>

</html>

templates/components/category_card.html
<section class="category-card-wrapper">
    <a href="{% url 'places:detail-category' pk=card_id %}">
        <section class="category-card">
            <h4 style="color: rgb(46, 46, 46);">{{ card_name }}</h4>
        </section>
    </a>
</section>

templates/components/comment_card.html
<blockquote class="comment-card">
    <h4 class="comment-author">{{ card_author }}</h4>
    <p class="comment-body">{{ card_text | linebreaks }}</p>
    <p class="comment-date"><b>{{ card_date | date:"Y/n/j" }}</b> às <b>{{ card_date | time:"H:i:s"}}</b></p>
</blockquote>

templates/components/feature.html
<section class="feature-card">
    <img class="feature-img" src="{{ feature_pic }}" alt="feature-img">
    <h3>{{ feature_name }}</h3>
    <p>{{ feature_desc }}</p>
</section>

templates/components/footer.html
<footer class="footer-global">
    <p>Mundo Aberto © 2023 — PMR3304</p>
</footer>

templates/components/head.html
{% load static %}

<head>
    <html lang="br"></html>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <title>Mundo Aberto | {{ title }}</title>
</head>

templates/components/header.html
{% load static %}

<header class="header-global">
    <h1 class="header-title">Mundo Aberto</h1>
    <nav class="header-links">
        <a class="header-item" href="{% url 'index' %}">Home</a>
        <a class="header-item" href="{% url 'about' %}">Sobre</a>
        <a class="header-item" href="{% url 'places:index' %}">Lugares</a>
        <a class="header-item" href="{% url 'places:categories' %}">Regiões</a>
    </nav>
</header>

templates/components/place_card.html
<section class="place-card-wrapper">
    <a href="{% url 'places:detail' pk=card_id %}">
        <section class="place-card">
                <img src="{{ card_picture }}" alt="place-card-pic" />
                <section class="place-card-text">
                    <h3>{{ card_name }}</h3>
                    <p>{{ card_date | date:"M. d, Y" }}<br />{{ card_date | time:"H:i"}}</p>
                </section>
        </section>
    </a>
</section>